### PR TITLE
urukul/v1.3 changes: add osc_en_n and mmcx_osc_sel

### PR DESCRIPTION
**Pull request by hartytp**
* add new mux to select between the XO and MMCX
* power down XO whenever it is not selected by the two muxes
* tp3 and tp4 connected to mmcx_osc_sel and osc_en_n in hardware

### CODE REVIEW

**Comment by hartytp** [comment]
Binaries available in hartytp/urukul/releases

**Comment by jordens** [comment]
Thanks. Functionality-wise this is fine. But I'd suggest two things:

* I'd leave the dummy bit alone and use the next unused bit after IO_RST. I think the dummy bit was doing something in older versions. I'd not repurpose it before running out of other bits.
* Do we really need to increment the protocol version? The new bit and will just be a NOP on older hardware. And the testpoint stuff is not part of the protocol anyway. That makes v1.2 and v1.3 transparently compatible w.r.t. cpld gateware, hardware, artiq. I'd just document that instead in ARTIQ. That also allows the same cpld gateware to be used on all of v1.0-v1.3. Or am I overlooking something?

**Review by jordens — CHANGES_REQUESTED** [review]
Thanks. Functionality-wise this is fine. But I'd suggest two things:

I'd leave the dummy bit alone and use the next unused bit after IO_RST. I think the dummy bit was doing something in older versions. I'd not repurpose it before running out of other bits.
Do we really need to increment the protocol version? The new bit and will just be a NOP on older hardware. And the testpoint stuff is not part of the protocol anyway. That makes v1.2 and v1.3 transparently compatible w.r.t. cpld gateware, hardware, artiq. I'd just document that instead in ARTIQ. That also allows the same cpld gateware to be used on all of v1.0-v1.3. Or am I overlooking something?

**Comment by hartytp** [comment]
> I'd leave the dummy bit alone and use the next unused bit after IO_RST. I think the dummy bit was doing something in older versions. I'd not repurpose it before running out of other bits.

Makes sense. I didn't think there were any boards left in the wild with that bit used any more, so it made sense to repurpose it, but happy to add a bit after IO_RST instead.

> Do we really need to increment the protocol version?

No, we don't *need* it, but incrementing it allows for a stricter check on hardware/software compatibility, which seems worthwhile to me.

My assumption is that, given the somewhat haphazard nature of these things, some v1.3 hardware has been/will be shipped with the old CPLD code. If we don't increment the CPLD version number then users will not have an easy means of checking for hardware/gateware mismatches; they will just find that some clocking options silently fail. That seems non-ideal to me. Having a fixed CPLD version for each hardware rev seems like a cleaner method of doing this.

Moreover, IME users can be quite bad at locating the correct schematic version for their hardware and may easily get confused over what clocking options are supported on their hardware. Again, without incrementing the CPLD revision, using old hardware with new clocking options will not result in a run-time error, just red lights on the board and wasted time.

Having said that, I don't feel strongly about any of this, so happy to leave the final call to you -- let me know what you want and I'll amend the PR accordingly.

**Comment by jordens** [comment]
But with the old gateware on v1.3 boards the same (stuff silently failing) will happen (and does right now), right? Flashing wrong gateware on the hardware is always pretty easy.
I'd really like to see progress on using the EEPROMs to encode the hardware revision and check that (m-labs/artiq#955, m-labs/artiq#1118, m-labs/artiq#355).
Overall, let's be pragmatic here with the cpld gateware. Something that was silent before (selecting XO vs MMCX) is still silent/NOP on old hardware. And we don't open new traps by multiplying protocol versions or having different builds for different hardware versions.

**Comment by hartytp** [comment]
@jordens done. Will rebuild and test now

**Comment by hartytp** [comment]
binaries https://github.com/hartytp/urukul/releases/tag/v1.3rc2

**Comment by jordens** [comment]
squashed, applied, tested. thanks!
https://github.com/quartiq/urukul/commit/fccf64d392fc7c184a0cf78d104d8fefe751429c
released as https://github.com/quartiq/urukul/releases/tag/v1.3

**Comment by hartytp** [comment]
thanks

**Comment by hartytp** [comment]
artiq commit coming up when I get half an hour at my desk...

**Pull request closed without merging**
