### PR TITLE
Added urukul/v1.3 support

### PR DESCRIPTION
**Pull request by atcher0**
Changes:
 - added clock mux that selects between MMCX and oscillator
 - added oscillator enable

### CODE REVIEW

**Comment by jordens** [comment]
Thanks. Could you coordinate with @hartytp?

**Comment by hartytp** [comment]
@atcher0 Here is what I have (just about to test with artiq): https://github.com/hartytp/urukul/commit/bc438061096e63998c7ea48323b6a32fcf8529bd

The main difference between our code is that I prefer the osc_en_n to be set automatically so that the oscillator is enabled if and only if it is selected by the muxes

We chose to use different bits for the new clock mux select, but I'm fairly indifferent as to how this is done.

**Comment by hartytp** [comment]
Anyone object to closing this in favor of #5?

**Comment by hartytp** [comment]
NB since you use a different bit for mmcx_osc_sel, this pr won't worth with the artiq PR I just submitted...

**Comment by atcher0** [comment]
ok, so let's stay with @hartytp version

**Pull request closed without merging**
